runtime: nodejs20

service: saintdong-platform

env_variables:
  NODE_ENV: production
  DB_SERVER: ''
  DB_PORT: ''
  DB_USER: ''
  # DB_PASSWORD 透過 GCP Secret Manager 或環境變數設定
  DB_DATABASE: ''

handlers:
  - url: /.*
    script: auto
